spring:
  application:
    name: question-service
  datasource:
    url: jdbc:mysql://localhost:3306/questiondb?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        dialect.storage_engine: innodb

server:
  port: 8090



